name: CI Pipeline

on:                     # Cuándo se ejecuta
  push:
    branches: [ main ]  # Solo cuando hay un push en main
  pull_request:
    branches: [ main ]

jobs:                   # Qué tareas ejecuta
  build:
    runs-on: ubuntu-latest  # Máquina virtual de GitHub

    steps:               # Pasos a ejecutar
      - name: Checkout code
        uses: actions/checkout@v4   # Descarga el código del repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias del client
        run: npm ci
        working-directory: client

      - name: Build del client
        run: npm run build
        working-directory: client

